from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('service-requests/', views.service_requests, name='service_requests'),
    path('service-requests/<int:sr_id>/reviewed/', views.sr_mark_reviewed, name='sr_mark_reviewed'),
    path('service-requests/<int:sr_id>/reject/', views.sr_reject, name='sr_reject'),
    path('service-requests/<int:sr_id>/schedule/', views.sr_schedule_appointment, name='sr_schedule_appointment'),
    path('service-requests/<int:sr_id>/delete/', views.sr_delete, name='sr_delete'),
    path('appointments/', views.appointments_list, name='appointments_list'),
    path('appointments/<int:appt_id>/edit/', views.edit_appointment, name='edit_appointment'),
    path('appointments/<int:appt_id>/update-status/', views.update_appointment_status, name='update_appointment_status'),
    path('appointments/<int:appt_id>/delete/', views.delete_appointment, name='delete_appointment'),
    path('blueprints/', views.blueprints_list, name='blueprints_list'),
    path('blueprints/<int:bp_id>/detail/', views.blueprint_detail, name='blueprint_detail'),
    path('blueprints/<int:bp_id>/new-revision/', views.create_blueprint_revision, name='create_blueprint_revision'),
    path('blueprints/<int:bp_id>/approve/', views.blueprint_approve, name='blueprint_approve'),
    path('blueprints/<int:bp_id>/request-revision/', views.blueprint_request_revision, name='blueprint_request_revision'),
    path('blueprints/<int:bp_id>/upload-file/', views.blueprint_upload_file, name='blueprint_upload_file'),
    path('blueprints/<int:bp_id>/delete/', views.delete_blueprint, name='delete_blueprint'),
    path('blueprints/files/<int:file_id>/delete/', views.blueprint_delete_file, name='blueprint_delete_file'),
    path('projects/', views.projects_list, name='projects_list'),
    path('projects/create/', views.create_project, name='create_project'),
    path('projects/<int:project_id>/assign-workers/', views.assign_project_workers, name='assign_project_workers'),
    path('projects/<int:project_id>/edit/', views.edit_project, name='edit_project'),
    path('projects/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('tasks/', views.tasks_list, name='tasks_list'),
    path('tasks/create/', views.create_task, name='create_task'),
    path('tasks/<int:task_id>/update-status/', views.task_update_status, name='task_update_status'),
    path('tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('clients/', views.clients_list, name='clients_list'),
    path('clients/create/', views.create_client, name='create_client'),
    path('clients/<int:client_id>/edit/', views.edit_client, name='edit_client'),
    path('clients/<int:client_id>/delete/', views.delete_client, name='delete_client'),
    path('employees/', views.employees_list, name='employees_list'),
    path('employees/create/', views.create_employee, name='create_employee'),
    path('employees/<int:profile_id>/assign-projects/', views.assign_projects, name='assign_projects'),
    path('employees/<int:profile_id>/edit/', views.edit_employee, name='edit_employee'),
    path('employees/<int:profile_id>/delete/', views.delete_employee, name='delete_employee'),
    path('api/services/', views.api_services, name='api_services'),
    path('api/submit-request/', views.api_submit_request, name='api_submit_request'),
]
