# Generated by Django 6.0.5 on 2026-05-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fire_protection', 'Fire Protection'), ('fdas', 'Fire Detection & Alarm System'), ('cctv', 'CCTV'), ('solar', 'Solar'), ('electrical', 'Electrical'), ('automation', 'Automation'), ('water_systems', 'Water Systems')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
