# Generated by Django 6.0.5 on 2026-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('fire_protection', 'Fire Protection'), ('fdas', 'FDAS / Fire Alarm'), ('wet_standpipe', 'Wet Standpipe'), ('fire_pump', 'Fire Pump'), ('cctv', 'CCTV'), ('intrusion', 'Intrusion'), ('lan_pabx', 'LAN / PABX'), ('automation', 'Automation'), ('solar', 'Solar'), ('electrical', 'Electrical'), ('motors', 'Motors'), ('wiring', 'Wiring'), ('mepf_works', 'MEPF Works'), ('water_pumps', 'Water Pumps'), ('compressor', 'Compressor'), ('water_tanks', 'Water Tanks')], max_length=50, unique=True),
        ),
    ]
