# Generated by Django 6.0.5 on 2026-05-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0002_blueprint_approved_at_blueprint_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
